version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/tellytv/go.xtream-codes
    steps:
      - checkout
      - run: go get -u github.com/onsi/gomega
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install --config=.gometalinter.json ./...
      - run: go test -v ./...
